# Generated by Django 4.1.1 on 2022-10-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_makermodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makermodel',
            name='Thumbnail',
            field=models.ImageField(null=True, upload_to='data/img/'),
        ),
    ]
